[build]
target = "x86_64-cotton_os.json"

[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]

[target.'cfg(target_os = "none")']
runner = "bootimage runner"

# Needed for Apple Silicon Macs
[env]
CC_x86_64_unknown_none = "x86_64-unknown-linux-gnu-gcc"
